name: Rust and Docker Build

on:
  push:
    branches: 
      - "main"
      - "dev"
  pull_request:
    branches: 
      - "main"
      - "dev"

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-build:
    name: Rust Build and Test
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Build Rust project
      - name: Build
        run: cargo build --release --verbose

      # Run tests
      - name: Run tests
        run: cargo test --verbose
